// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzsLdNyJcOj2cj5JdjPq8DW6BSmCATPqU',
    appId: '1:675657966749:web:786d6b7ee9c4f6ed3a6074',
    messagingSenderId: '675657966749',
    projectId: 'todo-app-94ffa',
    authDomain: 'todo-app-94ffa.firebaseapp.com',
    storageBucket: 'todo-app-94ffa.appspot.com',
    measurementId: 'G-GXQTT27BL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjl6RT5G5_9ky7o6wfFTTZ9UrYCucjb4o',
    appId: '1:675657966749:android:c1edcfe4d40e3b2a3a6074',
    messagingSenderId: '675657966749',
    projectId: 'todo-app-94ffa',
    storageBucket: 'todo-app-94ffa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdv6UEn3DY0lKfF6vIk0h9JaD_N3dEXvw',
    appId: '1:675657966749:ios:6aeedd1fa08441833a6074',
    messagingSenderId: '675657966749',
    projectId: 'todo-app-94ffa',
    storageBucket: 'todo-app-94ffa.appspot.com',
    iosBundleId: 'com.example.iamTraining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdv6UEn3DY0lKfF6vIk0h9JaD_N3dEXvw',
    appId: '1:675657966749:ios:6aeedd1fa08441833a6074',
    messagingSenderId: '675657966749',
    projectId: 'todo-app-94ffa',
    storageBucket: 'todo-app-94ffa.appspot.com',
    iosBundleId: 'com.example.iamTraining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzsLdNyJcOj2cj5JdjPq8DW6BSmCATPqU',
    appId: '1:675657966749:web:a4c2e098396cae1f3a6074',
    messagingSenderId: '675657966749',
    projectId: 'todo-app-94ffa',
    authDomain: 'todo-app-94ffa.firebaseapp.com',
    storageBucket: 'todo-app-94ffa.appspot.com',
    measurementId: 'G-WCCP952E68',
  );
}
